name: Build and push to another branch

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          echo "$CNAME" > public/CNAME
          npm run build
          touch dist/.nojekyll
        env:
          CNAME: ${{ vars.CNAME }}

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
